# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/repos/RFSoC_Controller_V2/vivado_project/RFSoC_Controller_V2.srcs/sources_1/bd/top_level/ip/top_level_auto_ds_0/top_level_auto_ds_0.xci
# IP: The module: 'top_level_auto_ds_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/repos/RFSoC_Controller_V2/vivado_project/RFSoC_Controller_V2.srcs/sources_1/bd/top_level/ip/top_level_auto_ds_0/top_level_auto_ds_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_auto_ds_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/repos/RFSoC_Controller_V2/vivado_project/RFSoC_Controller_V2.srcs/sources_1/bd/top_level/ip/top_level_auto_ds_0/top_level_auto_ds_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_auto_ds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/repos/RFSoC_Controller_V2/vivado_project/RFSoC_Controller_V2.srcs/sources_1/bd/top_level/ip/top_level_auto_ds_0/top_level_auto_ds_0.xci
# IP: The module: 'top_level_auto_ds_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/repos/RFSoC_Controller_V2/vivado_project/RFSoC_Controller_V2.srcs/sources_1/bd/top_level/ip/top_level_auto_ds_0/top_level_auto_ds_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_auto_ds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/repos/RFSoC_Controller_V2/vivado_project/RFSoC_Controller_V2.srcs/sources_1/bd/top_level/ip/top_level_auto_ds_0/top_level_auto_ds_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_auto_ds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
