# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/top_level/top_level.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level || ORIG_REF_NAME==top_level} -quiet] -quiet

# IP: bd/top_level/ip/top_level_zynq_ultra_ps_e_0_0/top_level_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==top_level_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axi_dma_0_0/top_level_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_axi_dma_0_0 || ORIG_REF_NAME==top_level_axi_dma_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_ps8_0_axi_periph_0/top_level_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_ps8_0_axi_periph_0 || ORIG_REF_NAME==top_level_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_rst_ps8_0_100M_0/top_level_rst_ps8_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_rst_ps8_0_100M_0 || ORIG_REF_NAME==top_level_rst_ps8_0_100M_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axi_smc_0/top_level_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_axi_smc_0 || ORIG_REF_NAME==top_level_axi_smc_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_xlconcat_0_0/top_level_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_xlconcat_0_0 || ORIG_REF_NAME==top_level_xlconcat_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_rfsoc_pl_ctrl_verilo_0_0/top_level_rfsoc_pl_ctrl_verilo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_rfsoc_pl_ctrl_verilo_0_0 || ORIG_REF_NAME==top_level_rfsoc_pl_ctrl_verilo_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_usp_rf_data_converter_0_0/top_level_usp_rf_data_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_usp_rf_data_converter_0_0 || ORIG_REF_NAME==top_level_usp_rf_data_converter_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axi_gpio_0_0/top_level_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_axi_gpio_0_0 || ORIG_REF_NAME==top_level_axi_gpio_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_rst_ps8_0_100M_1/top_level_rst_ps8_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_rst_ps8_0_100M_1 || ORIG_REF_NAME==top_level_rst_ps8_0_100M_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_gpio_buffer_0_0/top_level_gpio_buffer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_gpio_buffer_0_0 || ORIG_REF_NAME==top_level_gpio_buffer_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axis_data_fifo_0_0/top_level_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_axis_data_fifo_0_0 || ORIG_REF_NAME==top_level_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axis_data_fifo_1_0/top_level_axis_data_fifo_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_axis_data_fifo_1_0 || ORIG_REF_NAME==top_level_axis_data_fifo_1_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axis_data_fifo_1_1/top_level_axis_data_fifo_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_axis_data_fifo_1_1 || ORIG_REF_NAME==top_level_axis_data_fifo_1_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_system_ila_0_0/top_level_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_system_ila_0_0 || ORIG_REF_NAME==top_level_system_ila_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_system_ila_1_0/top_level_system_ila_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_system_ila_1_0 || ORIG_REF_NAME==top_level_system_ila_1_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_xbar_0/top_level_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_xbar_0 || ORIG_REF_NAME==top_level_xbar_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axis_tlast_slice_0_0/top_level_axis_tlast_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_axis_tlast_slice_0_0 || ORIG_REF_NAME==top_level_axis_tlast_slice_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_auto_ds_0/top_level_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_auto_ds_0 || ORIG_REF_NAME==top_level_auto_ds_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_auto_pc_0/top_level_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_auto_pc_0 || ORIG_REF_NAME==top_level_auto_pc_0} -quiet] -quiet

# XDC: bd/top_level/top_level_ooc.xdc
