# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/repos/RFSoC_Controller_V2/vivado_project/RFSoC_Controller_V2.srcs/sources_1/bd/top_level/ip/top_level_system_ila_1_0/top_level_system_ila_1_0.xci
# IP: The module: 'top_level_system_ila_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/repos/RFSoC_Controller_V2/vivado_project/RFSoC_Controller_V2.srcs/sources_1/bd/top_level/ip/top_level_system_ila_1_0/bd_0/bd_5bec.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5bec || ORIG_REF_NAME==bd_5bec} -quiet] -quiet

# IP: d:/repos/RFSoC_Controller_V2/vivado_project/RFSoC_Controller_V2.srcs/sources_1/bd/top_level/ip/top_level_system_ila_1_0/bd_0/ip/ip_0/bd_5bec_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5bec_ila_lib_0 || ORIG_REF_NAME==bd_5bec_ila_lib_0} -quiet] -quiet

# IP: d:/repos/RFSoC_Controller_V2/vivado_project/RFSoC_Controller_V2.srcs/sources_1/bd/top_level/ip/top_level_system_ila_1_0/bd_0/ip/ip_1/bd_5bec_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5bec_g_inst_0 || ORIG_REF_NAME==bd_5bec_g_inst_0} -quiet] -quiet

# XDC: d:/repos/RFSoC_Controller_V2/vivado_project/RFSoC_Controller_V2.srcs/sources_1/bd/top_level/ip/top_level_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5bec_ila_lib_0 || ORIG_REF_NAME==bd_5bec_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/repos/RFSoC_Controller_V2/vivado_project/RFSoC_Controller_V2.srcs/sources_1/bd/top_level/ip/top_level_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5bec_ila_lib_0 || ORIG_REF_NAME==bd_5bec_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/repos/RFSoC_Controller_V2/vivado_project/RFSoC_Controller_V2.srcs/sources_1/bd/top_level/ip/top_level_system_ila_1_0/bd_0/ip/ip_0/bd_5bec_ila_lib_0_ooc.xdc

# XDC: d:/repos/RFSoC_Controller_V2/vivado_project/RFSoC_Controller_V2.srcs/sources_1/bd/top_level/ip/top_level_system_ila_1_0/bd_0/bd_5bec_ooc.xdc

# XDC: d:/repos/RFSoC_Controller_V2/vivado_project/RFSoC_Controller_V2.srcs/sources_1/bd/top_level/ip/top_level_system_ila_1_0/top_level_system_ila_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_system_ila_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/repos/RFSoC_Controller_V2/vivado_project/RFSoC_Controller_V2.srcs/sources_1/bd/top_level/ip/top_level_system_ila_1_0/top_level_system_ila_1_0.xci
# IP: The module: 'top_level_system_ila_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/repos/RFSoC_Controller_V2/vivado_project/RFSoC_Controller_V2.srcs/sources_1/bd/top_level/ip/top_level_system_ila_1_0/bd_0/bd_5bec.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5bec || ORIG_REF_NAME==bd_5bec} -quiet] -quiet

# IP: d:/repos/RFSoC_Controller_V2/vivado_project/RFSoC_Controller_V2.srcs/sources_1/bd/top_level/ip/top_level_system_ila_1_0/bd_0/ip/ip_0/bd_5bec_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5bec_ila_lib_0 || ORIG_REF_NAME==bd_5bec_ila_lib_0} -quiet] -quiet

# IP: d:/repos/RFSoC_Controller_V2/vivado_project/RFSoC_Controller_V2.srcs/sources_1/bd/top_level/ip/top_level_system_ila_1_0/bd_0/ip/ip_1/bd_5bec_g_inst_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5bec_g_inst_0 || ORIG_REF_NAME==bd_5bec_g_inst_0} -quiet] -quiet

# XDC: d:/repos/RFSoC_Controller_V2/vivado_project/RFSoC_Controller_V2.srcs/sources_1/bd/top_level/ip/top_level_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5bec_ila_lib_0 || ORIG_REF_NAME==bd_5bec_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/repos/RFSoC_Controller_V2/vivado_project/RFSoC_Controller_V2.srcs/sources_1/bd/top_level/ip/top_level_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5bec_ila_lib_0 || ORIG_REF_NAME==bd_5bec_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/repos/RFSoC_Controller_V2/vivado_project/RFSoC_Controller_V2.srcs/sources_1/bd/top_level/ip/top_level_system_ila_1_0/bd_0/ip/ip_0/bd_5bec_ila_lib_0_ooc.xdc

# XDC: d:/repos/RFSoC_Controller_V2/vivado_project/RFSoC_Controller_V2.srcs/sources_1/bd/top_level/ip/top_level_system_ila_1_0/bd_0/bd_5bec_ooc.xdc

# XDC: d:/repos/RFSoC_Controller_V2/vivado_project/RFSoC_Controller_V2.srcs/sources_1/bd/top_level/ip/top_level_system_ila_1_0/top_level_system_ila_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_system_ila_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
